package com.github.taymindis.nio.channeling;

enum ChannelingTask {
    DO_CONNECT,
    DO_PROXY_CONNECT,
    DO_READ,
    DO_WRITE,
    DO_PROXY_SSL_CONNECT_READ,
    DO_PROXY_SSL_CONNECT_WRITE,
    DO_CLOSE,
    DO_IDLE,

//    DO_REMOVE_EAGER_READ,
//    DO_REMOVE_EAGER_READ_FROM_READ,
//    DO_REMOVE_EAGER_READ_FROM_WRITE,
//    DO_REMOVE_EAGER_READ_FROM_CLOSE,
//    DO_REMOVE_EAGER_READ_FROM_IDLE,

    WHEN_READ_BYTEBUFFER,
    WHEN_WRITE_BYTEBUFFER,
    WHEN_SOCKETCHANNEL,
    WHEN_CHANNELING_SOCKET,
    WHEN_CONNECT_STATUS,
    WHEN_READWRITE_PROCESS,
    WHEN_CLOSING_PROCESS,

}
